services:
  webapi:
    build: .
    container_name: current-messages-net
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AllowedOrigins__0: ${ALLOWED_ORIGINS}
      Jwt__Key: ${JWT_KEY}
      ConnectionStrings__DefaultConnection: >
        Host=db;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}

  db:
    user: '0:0'
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres15
    ports:
      - "5432:5432"
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
